<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CustomersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('customers')->delete();
        
        \DB::table('customers')->insert(array (
            0 => 
            array (
                'id' => 1,
                'firstname' => 'Prashant',
                'lastname' => 'Chauhan',
                'username' => 'webreca',
                'email' => 'webreca@gmail.com',
                'total_review' => 5,
                'avg_rating' => '3.00',
                'country_code' => 'IN',
                'mobile' => '9999577620',
                'ref_by' => 0,
                'balance' => '0.00000000',
                'password' => '$2y$10$bC2IJhFFwpgwV7/k6eNx6OwBppaXlKis25Cigw0SRowBuk/LxjrGK',
                'image' => '674af1457ed241732964677.jpg',
                'address' => '{"country":"India","address":"C-6, Sector 7","state":"Uttar Pradesh","zip":"201301","city":"Noida"}',
                'gender' => 'Male',
                'status' => 1,
                'kyc_data' => '[{"name":"Full Name","type":"text","value":"Prashant Chauhan"},{"name":"NID Number","type":"text","value":"262370258990"},{"name":"Gender","type":"select","value":"Male"},{"name":"You Hobby","type":"checkbox","value":["Programming","Traveling","Others"]},{"name":"NID Photo","type":"file","value":"2024\\/12\\/17\\/676184e73a52a1734444263.png"},{"name":"Mobile","type":"text","value":"9874589657"}]',
                'kv' => 1,
                'ev' => 1,
                'sv' => 1,
                'reg_step' => 1,
                'ver_code' => NULL,
                'ver_code_send_at' => NULL,
                'ts' => 0,
                'tv' => 1,
                'tsc' => NULL,
                'ban_reason' => NULL,
                'remember_token' => 'JbRltbSioWBcWEOvc07u7SI84xkz8EtNJyGjEoAqXjgstffRv0XHuJShW6hB',
                'created_at' => '2024-11-28 01:49:39',
                'updated_at' => '2024-12-23 20:49:44',
            ),
            1 => 
            array (
                'id' => 2,
                'firstname' => 'Srijan',
                'lastname' => 'Pratap',
                'username' => 'n2rtech',
                'email' => 'mailme9999577620@gmail.com',
                'total_review' => 3,
                'avg_rating' => '4.00',
                'country_code' => 'IN',
                'mobile' => '9555108745',
                'ref_by' => 0,
                'balance' => '0.00000000',
                'password' => '$2y$10$53/jQT1GT5TeGnXXEck7kuun7NsoPd3CQIUjqOhpgpvSb1mMsuZdi',
                'image' => '674af1457ed241732964677.jpg',
                'address' => '{"country":"India","address":"C-6, Sector 7","state":"Uttar Pradesh","zip":"201301","city":"Noida"}',
                'gender' => 'Male',
                'status' => 1,
                'kyc_data' => '[{"name":"Full Name","type":"text","value":"Srijan Pratap"},{"name":"NID Number","type":"text","value":"262370258991"},{"name":"Gender","type":"select","value":"Male"},{"name":"You Hobby","type":"checkbox","value":["Programming","Traveling","Others"]},{"name":"NID Photo","type":"file","value":"2024\\/12\\/17\\/676184e73a52a1734444263.png"},{"name":"Mobile","type":"text","value":"9555108745"}]',
                'kv' => 1,
                'ev' => 1,
                'sv' => 1,
                'reg_step' => 1,
                'ver_code' => NULL,
                'ver_code_send_at' => NULL,
                'ts' => 0,
                'tv' => 1,
                'tsc' => NULL,
                'ban_reason' => NULL,
                'remember_token' => 'g86wbxKb1lElnHu1gZOZE2gZA3OKH4MF4sLOQjmaNKoSEGWJDybxGpuPRVVE',
                'created_at' => '2024-11-28 01:49:39',
                'updated_at' => '2024-12-18 01:34:23',
            ),
            2 => 
            array (
                'id' => 3,
                'firstname' => 'Krishna',
                'lastname' => 'Mishra',
                'username' => 'wipro',
                'email' => 'er.krishnamishra1@gmail.com',
                'total_review' => 4,
                'avg_rating' => '5.00',
                'country_code' => 'IN',
                'mobile' => '8800611165',
                'ref_by' => 0,
                'balance' => '0.00000000',
                'password' => '$2y$10$53/jQT1GT5TeGnXXEck7kuun7NsoPd3CQIUjqOhpgpvSb1mMsuZdi',
                'image' => '674af1457ed241732964677.jpg',
                'address' => '{"country":"India","address":"B-23 Malviya nagar, West Delhi","state":"New Delhi","zip":"110006","city":"Delhi"}',
                'gender' => 'Male',
                'status' => 1,
                'kyc_data' => '[{"name":"Full Name","type":"text","value":"Krishna Mishra"},{"name":"NID Number","type":"text","value":"262370258992"},{"name":"Gender","type":"select","value":"Male"},{"name":"You Hobby","type":"checkbox","value":["Programming","Traveling","Others"]},{"name":"NID Photo","type":"file","value":"2024\\/12\\/17\\/676184e73a52a1734444263.png"},{"name":"Mobile","type":"text","value":"8800611165"}]',
                'kv' => 1,
                'ev' => 1,
                'sv' => 1,
                'reg_step' => 1,
                'ver_code' => NULL,
                'ver_code_send_at' => NULL,
                'ts' => 0,
                'tv' => 1,
                'tsc' => NULL,
                'ban_reason' => NULL,
                'remember_token' => 'g86wbxKb1lElnHu1gZOZE2gZA3OKH4MF4sLOQjmaNKoSEGWJDybxGpuPRVVE',
                'created_at' => '2024-11-28 01:49:39',
                'updated_at' => '2024-12-18 01:34:23',
            ),
            3 => 
            array (
                'id' => 4,
                'firstname' => 'estate',
                'lastname' => 'masters',
                'username' => 'estate',
                'email' => 'info.estatemasters@gmail.com',
                'total_review' => NULL,
                'avg_rating' => NULL,
                'country_code' => NULL,
                'mobile' => NULL,
                'ref_by' => 0,
                'balance' => '0.00000000',
                'password' => '$2y$10$1Zd9KUGBWA5sGOtStJbD6OLzPfo2t5k/eQRfpg2hX.33Rfkeot6/i',
                'image' => NULL,
                'address' => '{"country":null,"address":"noida","state":"uttar pradesh","zip":"201309","city":"Noida"}',
                'gender' => 'Male',
                'status' => 1,
                'kyc_data' => NULL,
                'kv' => 0,
                'ev' => 1,
                'sv' => 1,
                'reg_step' => 1,
                'ver_code' => NULL,
                'ver_code_send_at' => NULL,
                'ts' => 0,
                'tv' => 1,
                'tsc' => NULL,
                'ban_reason' => NULL,
                'remember_token' => NULL,
                'created_at' => '2024-12-21 20:30:59',
                'updated_at' => '2024-12-21 20:31:40',
            ),
            4 => 
            array (
                'id' => 5,
                'firstname' => NULL,
                'lastname' => NULL,
                'username' => NULL,
                'email' => 'sandipva55@gmail.com',
                'total_review' => NULL,
                'avg_rating' => NULL,
                'country_code' => NULL,
                'mobile' => NULL,
                'ref_by' => 0,
                'balance' => '0.00000000',
                'password' => '$2y$10$qau.MSjq6GIYoO67tTRxAul5yOQhCKxU/MEQa1.ibw8VOU24Rssmm',
                'image' => NULL,
                'address' => '{"address":"","state":"","zip":"","country":null,"city":""}',
                'gender' => NULL,
                'status' => 1,
                'kyc_data' => NULL,
                'kv' => 0,
                'ev' => 1,
                'sv' => 1,
                'reg_step' => 0,
                'ver_code' => NULL,
                'ver_code_send_at' => NULL,
                'ts' => 0,
                'tv' => 1,
                'tsc' => NULL,
                'ban_reason' => NULL,
                'remember_token' => NULL,
                'created_at' => '2024-12-23 03:34:19',
                'updated_at' => '2024-12-23 03:34:19',
            ),
            5 => 
            array (
                'id' => 6,
                'firstname' => 'Test',
                'lastname' => 'Mohit',
                'username' => 'testuser',
                'email' => 'mohitparwal2103@gmail.com',
                'total_review' => NULL,
                'avg_rating' => NULL,
                'country_code' => NULL,
                'mobile' => NULL,
                'ref_by' => 0,
                'balance' => '0.00000000',
                'password' => '$2y$10$bDSaEp.VGp2r08fZb0bwGeOlOTZE/dQ1ZXvdILNxfDo5YtZHtDvBm',
                'image' => NULL,
                'address' => '{"country":null,"address":"delhi","state":"delhi","zip":"122164","city":"delhi"}',
                'gender' => 'Male',
                'status' => 1,
                'kyc_data' => NULL,
                'kv' => 0,
                'ev' => 1,
                'sv' => 1,
                'reg_step' => 1,
                'ver_code' => NULL,
                'ver_code_send_at' => NULL,
                'ts' => 0,
                'tv' => 1,
                'tsc' => NULL,
                'ban_reason' => NULL,
                'remember_token' => NULL,
                'created_at' => '2024-12-29 20:09:57',
                'updated_at' => '2024-12-29 20:10:23',
            ),
            6 => 
            array (
                'id' => 7,
                'firstname' => 'Vikash',
                'lastname' => 'Tripathi',
                'username' => 'Vikash 1',
                'email' => 'citymartgkp@gmail.com',
                'total_review' => NULL,
                'avg_rating' => NULL,
                'country_code' => NULL,
                'mobile' => NULL,
                'ref_by' => 0,
                'balance' => '0.00000000',
                'password' => '$2y$10$MNIr1wAjMMPfIjp/kNjYtuQWuEdiPfZy0WQWd87UNpiLxdhNZs.wq',
                'image' => NULL,
                'address' => '{"country":null,"address":"Gorakhpur","state":"Uttar Pradesh","zip":"273010","city":"Gorakhpur"}',
                'gender' => 'Male',
                'status' => 1,
                'kyc_data' => NULL,
                'kv' => 0,
                'ev' => 1,
                'sv' => 1,
                'reg_step' => 1,
                'ver_code' => NULL,
                'ver_code_send_at' => NULL,
                'ts' => 0,
                'tv' => 1,
                'tsc' => NULL,
                'ban_reason' => NULL,
                'remember_token' => NULL,
                'created_at' => '2024-12-30 14:50:04',
                'updated_at' => '2024-12-30 14:51:22',
            ),
            7 => 
            array (
                'id' => 8,
                'firstname' => 'Priya',
                'lastname' => 'Jyoti',
                'username' => 'priyajyoti',
                'email' => 'priyajyoti307@gmail.com',
                'total_review' => NULL,
                'avg_rating' => NULL,
                'country_code' => 'IN',
                'mobile' => '919988776655',
                'ref_by' => 0,
                'balance' => '0.00000000',
                'password' => '$2y$10$rQnJf.WJPeqWB4vKP.0ct.EIMMqmaXVGsqiHnNoGttVpGDsYbWcdO',
                'image' => NULL,
                'address' => '{"country":"India","address":"Delhi","state":"Delhi","zip":"110049","city":"Delhi"}',
                'gender' => 'Female',
                'status' => 1,
                'kyc_data' => NULL,
                'kv' => 0,
                'ev' => 1,
                'sv' => 1,
                'reg_step' => 1,
                'ver_code' => NULL,
                'ver_code_send_at' => NULL,
                'ts' => 0,
                'tv' => 1,
                'tsc' => NULL,
                'ban_reason' => NULL,
                'remember_token' => 'lq9lj1KuCLcVj3nLff2EyxqjbxfQA3mpXsz33t9jjVTcJeNCb97hj4s0guwP',
                'created_at' => '2024-12-31 21:45:01',
                'updated_at' => '2024-12-31 21:49:16',
            ),
        ));
        
        
    }
}