<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PropertiesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('properties')->delete();
        
        \DB::table('properties')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 1,
                'category_id' => 1,
                'type_id' => 1,
                'tab_id' => NULL,
                'title' => 'De Pavilion Hotel',
                'units' => 1,
                'capacity' => 10,
                'bed' => 9,
                'bedroom' => 5,
                'bath' => 5,
                'description' => '<p><strong>Lorem Ipsum</strong> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</p>',
                'location' => '250-A, Road No. 6, Block RZ, Mahipalpur Village',
                'city' => 'Gurugram',
                'state' => 'Haryana',
                'country' => 'India',
                'lat' => '77.511381',
                'lon' => '28.4656',
                'property_detail' => '{"<i class=\\"fas fa-temperature-low\\"><\\/i>":"AC"}',
                'regular_price' => '400.00000000',
                'discount_price' => '300.00000000',
                'status' => 1,
                'is_featured' => 1,
                'total_review' => 2,
                'avg_rating' => '5.00',
                'created_at' => '2024-11-18 18:11:30',
                'updated_at' => '2024-11-18 18:12:13',
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => 2,
                'category_id' => 2,
                'type_id' => 2,
                'tab_id' => NULL,
                'title' => 'Fab Hotel ',
                'units' => 1,
                'capacity' => 50,
                'bed' => 6,
                'bedroom' => 4,
                'bath' => 15,
                'description' => '<p><strong>Lorem Ipsum</strong> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</p>',
                'location' => 'Bhama Shah Marg, opp. Kirpal Bagh, Ishwar Colony, Ashram',
                'city' => 'New Delhi',
                'state' => 'Delhi',
                'country' => 'India',
                'lat' => '77.511381',
                'lon' => '28.4656',
                'property_detail' => '{"<i class=\\"fas fa-temperature-low\\"><\\/i>":"AC"}',
                'regular_price' => '600.00000000',
                'discount_price' => '500.00000000',
                'status' => 1,
                'is_featured' => 1,
                'total_review' => 3,
                'avg_rating' => '4.00',
                'created_at' => '2024-11-18 18:11:30',
                'updated_at' => '2024-11-18 18:12:13',
            ),
            2 => 
            array (
                'id' => 3,
                'user_id' => 6,
                'category_id' => 3,
                'type_id' => 3,
                'tab_id' => NULL,
                'title' => 'Svelte Delhi
',
                'units' => 1,
                'capacity' => 50,
                'bed' => 6,
                'bedroom' => 4,
                'bath' => 15,
                'description' => '<p><strong>Lorem Ipsum</strong> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</p>',
                'location' => 'A- 3, District Centre, Saket, Select City Walk Mall, Saket',
                'city' => 'New Delhi',
                'state' => 'Delhi',
                'country' => 'India',
                'lat' => '77.511381',
                'lon' => '28.4656',
                'property_detail' => '{"<i class=\\"fas fa-temperature-low\\"><\\/i>":"AC"}',
                'regular_price' => '600.00000000',
                'discount_price' => '550.00000000',
                'status' => 1,
                'is_featured' => 1,
                'total_review' => 3,
                'avg_rating' => '4.00',
                'created_at' => '2024-11-18 18:11:30',
                'updated_at' => '2024-11-18 18:12:13',
            ),
            3 => 
            array (
                'id' => 4,
                'user_id' => 4,
                'category_id' => 4,
                'type_id' => 1,
                'tab_id' => NULL,
                'title' => 'Royal Plaza',
                'units' => 1,
                'capacity' => 2,
                'bed' => 1,
                'bedroom' => 1,
                'bath' => 1,
                'description' => '<p><strong>Lorem Ipsum</strong> is simply dummy te...',
                'location' => 'Greater Noida, Gautam Buddha Nagar, Uttar Pradesh, India',
                'city' => 'Gautam Buddha Nagar',
                'state' => 'Uttar Pradesh',
                'country' => 'India',
                'lat' => '77.511381',
                'lon' => '28.4656',
                'property_detail' => '{"<i class=\\"fas fa-temperature-low\\"><\\/i>":"AC"}',
                'regular_price' => '200.00000000',
                'discount_price' => '100.00000000',
                'status' => 1,
                'is_featured' => 1,
                'total_review' => 4,
                'avg_rating' => '3.00',
                'created_at' => '2024-12-10 01:17:40',
                'updated_at' => '2024-12-10 01:28:42',
            ),
            4 => 
            array (
                'id' => 5,
                'user_id' => 5,
                'category_id' => 5,
                'type_id' => 2,
                'tab_id' => 2,
                'title' => 'Penthouse',
                'units' => 1,
                'capacity' => 5,
                'bed' => 5,
                'bedroom' => 5,
                'bath' => 2,
                'description' => '<p><strong>Lorem Ipsum</strong> is simply dummy te...',
                'location' => 'Pari Chowk, Gautam Buddha Nagar, Uttar Pradesh, India',
                'city' => 'Gautam Buddha Nagar',
                'state' => 'Uttar Pradesh',
                'country' => 'India',
                'lat' => '77.511292',
                'lon' => '28.465239',
                'property_detail' => '{"<i class=\\"fab fa-accessible-icon\\"><\\/i>":"Air Cinonditioner"}',
                'regular_price' => '500.00000000',
                'discount_price' => '450.00000000',
                'status' => 1,
                'is_featured' => 1,
                'total_review' => 5,
                'avg_rating' => '3.50',
                'created_at' => '2024-12-11 23:36:00',
                'updated_at' => '2024-12-11 23:49:38',
            ),
            5 => 
            array (
                'id' => 6,
                'user_id' => 6,
                'category_id' => 6,
                'type_id' => 3,
                'tab_id' => 4,
                'title' => '2 BHK Penthouse Noida',
                'units' => 1,
                'capacity' => 6,
                'bed' => 2,
                'bedroom' => 3,
                'bath' => 3,
                'description' => '<p>Looking for a premium penthouse in the prime location of Saket, Noida.<br>&nbsp;</p><ul><li>Your search ends here! Presenting a beautiful 2BHK penthouse available for rent in the prestigious Freedom Fighters Enclave.</li><li>Set in a gated society, this property is located in a safe and secure locality, ideal for families.</li><li>Spanning across 1000 square feet, this semi-furnished penthouse offers a spacious living area designed to meet the modern standards of comfort and luxury.</li><li>The property consists of 2 bedrooms and 2 bathrooms, making it perfect for a small family or working professionals.</li><li>With schools in close vicinity, you can ensure your childs education is never compromised.</li></ul>',
                'location' => 'Noida, Gautam Buddha Nagar, Uttar Pradesh, India',
                'city' => 'Gautam Buddha Nagar',
                'state' => 'Uttar Pradesh',
                'country' => 'India',
                'lat' => '77.325751',
                'lon' => '28.571076',
                'property_detail' => '{"<i class=\\"fab fa-accessible-icon\\"><\\/i>":"Wheelchair","<i class=\\"fas fa-tv\\"><\\/i>":"Television","<i class=\\"las la-wind\\"><\\/i>":"Air Conditioning"}',
                'regular_price' => '500.00000000',
                'discount_price' => '430.00000000',
                'status' => 1,
                'is_featured' => 1,
                'total_review' => 6,
                'avg_rating' => '4.50',
                'created_at' => '2024-11-30 18:53:45',
                'updated_at' => '2024-12-06 01:30:49',
            ),
            6 => 
            array (
                'id' => 7,
                'user_id' => 7,
                'category_id' => 7,
                'type_id' => 3,
                'tab_id' => 4,
                'title' => 'Golden Keys Inn',
                'units' => 1,
                'capacity' => 6,
                'bed' => 2,
                'bedroom' => 3,
                'bath' => 3,
                'description' => '<p>Looking for a <b>Golden Keys Inn</b> in the prime location of Saket, Noida.<br>&nbsp;</p><ul><li>Your search ends here! Presenting a beautiful 2BHK penthouse available for rent in the prestigious Freedom Fighters Enclave.</li><li>Set in a gated society, this property is located in a safe and secure locality, ideal for families.</li><li>Spanning across 1000 square feet, this semi-furnished penthouse offers a spacious living area designed to meet the modern standards of comfort and luxury.</li><li>The property consists of 2 bedrooms and 2 bathrooms, making it perfect for a small family or working professionals.</li><li>With schools in close vicinity, you can ensure your childs education is never compromised.</li></ul>',
                'location' => 'Noida, Gautam Buddha Nagar, Uttar Pradesh, India',
                'city' => 'Gautam Buddha Nagar',
                'state' => 'Uttar Pradesh',
                'country' => 'India',
                'lat' => '77.325751',
                'lon' => '28.571076',
                'property_detail' => '{"<i class=\\"fab fa-accessible-icon\\"><\\/i>":"Wheelchair","<i class=\\"fas fa-tv\\"><\\/i>":"Television","<i class=\\"las la-wind\\"><\\/i>":"Air Conditioning"}',
                'regular_price' => '750.00000000',
                'discount_price' => '680.00000000',
                'status' => 1,
                'is_featured' => 1,
                'total_review' => 5,
                'avg_rating' => '5.00',
                'created_at' => '2024-11-30 18:53:45',
                'updated_at' => '2024-12-06 01:30:49',
            ),
            7 => 
            array (
                'id' => 9,
                'user_id' => 6,
                'category_id' => 3,
                'type_id' => 3,
                'tab_id' => 4,
                'title' => 'Red Cottage Delhi',
                'units' => 1,
                'capacity' => 50,
                'bed' => 6,
                'bedroom' => 4,
                'bath' => 15,
                'description' => '<p><strong>Red Cottage Delhi</strong> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</p>',
                'location' => 'B- 3, District Centre, Janakpuri, Delhi',
                'city' => 'New Delhi',
                'state' => 'Delhi',
                'country' => 'India',
                'lat' => '77.511381',
                'lon' => '28.4656',
                'property_detail' => '{"<i class=\\"fas fa-temperature-low\\"><\\/i>":"AC"}',
                'regular_price' => '20.00000000',
                'discount_price' => '10.00000000',
                'status' => 1,
                'is_featured' => 1,
                'total_review' => 4,
                'avg_rating' => '3.00',
                'created_at' => '2024-11-18 18:11:30',
                'updated_at' => '2024-12-24 14:59:45',
            ),
            8 => 
            array (
                'id' => 10,
                'user_id' => 9,
                'category_id' => 1,
                'type_id' => 1,
                'tab_id' => NULL,
                'title' => 'Beldivers Towers',
                'units' => 1,
                'capacity' => 15,
                'bed' => 8,
                'bedroom' => 3,
                'bath' => 15,
                'description' => '<p>jlishuliasdfhishfwahfuiwfuihfilsdhfishfjibhfjlsdbhfjsdfiaswhdhufh</p>',
                'location' => 'Sector 21, Gurugram, Haryana, India',
                'city' => 'Gurugram',
                'state' => 'Haryana',
                'country' => 'India',
                'lat' => '77.073282',
                'lon' => '28.514531',
                'property_detail' => '{"<i class=\\"fas fa-wifi\\"><\\/i>":"Free wifi"}',
                'regular_price' => '1500.00000000',
                'discount_price' => '1250.00000000',
                'status' => 1,
                'is_featured' => 0,
                'total_review' => NULL,
                'avg_rating' => NULL,
                'created_at' => '2024-12-29 20:04:39',
                'updated_at' => '2024-12-29 20:08:11',
            ),
            9 => 
            array (
                'id' => 11,
                'user_id' => 10,
                'category_id' => 1,
                'type_id' => 1,
                'tab_id' => NULL,
                'title' => 'Camellia',
                'units' => 1,
                'capacity' => 6,
                'bed' => 3,
                'bedroom' => 1,
                'bath' => 1,
                'description' => '<p>juiwuihuiwhjuiwhhwuihwuhwhruiwhruipwehuipfhwifhuiewfh</p>',
                'location' => 'Dwarka Sector 21 Underpass, Sector 21, 110077, New Delhi, South West Delhi, Delhi, India',
                'city' => 'South West Delhi',
                'state' => 'Delhi',
                'country' => 'India',
                'lat' => '28.55213219943883',
                'lon' => '77.05791075832707',
                'property_detail' => '{"<i class=\\"fas fa-wifi\\"><\\/i>":"Free Wifi","<i class=\\"fas fa-apple-alt\\"><\\/i>":"Free Breakfast","<i class=\\"fas fa-utensils\\"><\\/i>":"Microwave"}',
                'regular_price' => '20.00000000',
                'discount_price' => '12.00000000',
                'status' => 1,
                'is_featured' => 0,
                'total_review' => NULL,
                'avg_rating' => NULL,
                'created_at' => '2024-12-29 20:34:11',
                'updated_at' => '2024-12-29 20:39:22',
            ),
            10 => 
            array (
                'id' => 12,
                'user_id' => 6,
                'category_id' => 3,
                'type_id' => 1,
                'tab_id' => 4,
                'title' => 'New Hotel',
                'units' => 1,
                'capacity' => 5,
                'bed' => 4,
                'bedroom' => 4,
                'bath' => 1,
                'description' => '<p>Lorem de ipsim</p>',
                'location' => 'Lieutenant Vijyant Thapar Marg, Naya Bans Village, 201301, Sector 2, Noida, Gautam Buddha Nagar, Uttar Pradesh, India',
                'city' => 'Gautam Buddha Nagar',
                'state' => 'Uttar Pradesh',
                'country' => 'India',
                'lat' => '28.582848521185554',
                'lon' => '77.31321924327062',
                'property_detail' => '{"<i class=\\"fab fa-500px\\"><\\/i>":"FRIDGE","<i class=\\"fas fa-tv\\"><\\/i>":"TELEVISION","<i class=\\"fas fa-dumbbell\\"><\\/i>":"GYM"}',
                'regular_price' => NULL,
                'discount_price' => NULL,
                'status' => 0,
                'is_featured' => 0,
                'total_review' => NULL,
                'avg_rating' => NULL,
                'created_at' => '2025-01-03 02:44:57',
                'updated_at' => '2025-01-04 13:39:40',
            ),
            11 => 
            array (
                'id' => 13,
                'user_id' => 6,
                'category_id' => 3,
                'type_id' => 1,
                'tab_id' => 4,
                'title' => 'New Silvester Stay',
                'units' => 3,
                'capacity' => 3,
                'bed' => 5,
                'bedroom' => 4,
                'bath' => 12,
                'description' => '<p>Lorem</p>',
                'location' => 'Noida, Gautam Buddha Nagar, Uttar Pradesh, India',
                'city' => 'Gautam Buddha Nagar',
                'state' => 'Uttar Pradesh',
                'country' => 'India',
                'lat' => '77.325751',
                'lon' => '28.571076',
                'property_detail' => '{"http:\\/\\/127.0.0.1:8000\\/storage\\/uploads\\/amenities\\/wifi.png":"Free Wi-Fi","http:\\/\\/127.0.0.1:8000\\/storage\\/uploads\\/amenities\\/swimming-pool.png":"Swimming Pool","http:\\/\\/127.0.0.1:8000\\/storage\\/uploads\\/amenities\\/in-house-restaurant.png":"In-House Restaurant","http:\\/\\/127.0.0.1:8000\\/storage\\/uploads\\/amenities\\/gym.png":"Gym","http:\\/\\/127.0.0.1:8000\\/storage\\/uploads\\/amenities\\/spa.png":"Spa","http:\\/\\/127.0.0.1:8000\\/storage\\/uploads\\/amenities\\/bar.png":"Bar","http:\\/\\/127.0.0.1:8000\\/storage\\/uploads\\/amenities\\/smart-tv.png":"Smart TV","http:\\/\\/127.0.0.1:8000\\/storage\\/uploads\\/amenities\\/hair-dryer.png":"Hair Dryer","http:\\/\\/127.0.0.1:8000\\/storage\\/uploads\\/amenities\\/air-conditioner.png":"Air Conditioner","http:\\/\\/127.0.0.1:8000\\/storage\\/uploads\\/amenities\\/free-parking.png":"Free Parking"}',
                'regular_price' => '1220.00000000',
                'discount_price' => '1000.00000000',
                'status' => 1,
                'is_featured' => 0,
                'total_review' => NULL,
                'avg_rating' => NULL,
                'created_at' => '2025-01-04 13:44:42',
                'updated_at' => '2025-01-04 15:58:06',
            ),
        ));
        
        
    }
}