<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'firstname' => 'Estate',
                'lastname' => 'Masters',
                'username' => 'estatemasters',
                'email' => 'info.estatemasters@gmail.com',
                'total_review' => 5,
                'avg_rating' => '3.00',
                'country_code' => 'IN',
                'mobile' => '917827500178',
                'ref_by' => 0,
                'balance' => '0.00000000',
                'password' => '$2y$10$yIfeM9a1bmhP9cV7E6Ef6ezsalFlUDj0k.ZqMr9pZktIMcpsd6uiS',
                'image' => NULL,
                'address' => '{"address":"2, 6th Floor, Building 2, Candor Techspace","city":"Noida","state":"Uttar pradesh","zip":"201309","country":"India"}',
                'status' => 1,
                'kyc_data' => NULL,
                'kv' => 1,
                'ev' => 1,
                'sv' => 1,
                'reg_step' => 1,
                'ver_code' => NULL,
                'ver_code_send_at' => NULL,
                'ts' => 1,
                'tv' => 1,
                'tsc' => NULL,
                'ban_reason' => NULL,
                'remember_token' => NULL,
                'created_at' => '2024-10-27 22:18:15',
                'updated_at' => '2024-10-27 22:22:04',
            ),
            1 => 
            array (
                'id' => 2,
                'firstname' => 'Sunny',
                'lastname' => 'Ahlawat',
                'username' => 'sandeep',
                'email' => 'sandip55@gmail.com',
                'total_review' => 5,
                'avg_rating' => '3.00',
                'country_code' => 'IN',
                'mobile' => '917303878702',
                'ref_by' => 0,
                'balance' => '0.00000000',
                'password' => '$2y$10$B.6g2FOyoBXVJQuSUCSrTewH7kNwAeP.YKOLLxn9rfkyZyVkn9vCq',
                'image' => NULL,
                'address' => '{"address":"3, 6th Floor, Building 2, Candor Techspace","city":"Noida","state":"Uttar pradesh","zip":"201309","country":"India"}',
                'status' => 1,
                'kyc_data' => NULL,
                'kv' => 0,
                'ev' => 0,
                'sv' => 0,
                'reg_step' => 0,
                'ver_code' => '943988',
                'ver_code_send_at' => '2024-11-18 11:45:49',
                'ts' => 0,
                'tv' => 1,
                'tsc' => NULL,
                'ban_reason' => NULL,
                'remember_token' => NULL,
                'created_at' => '2024-11-18 17:15:48',
                'updated_at' => '2024-11-18 17:22:19',
            ),
            2 => 
            array (
                'id' => 3,
                'firstname' => 'Kailash',
                'lastname' => 'Singh',
                'username' => 'kailashsingh',
                'email' => 'kailashsingh@gmail.com',
                'total_review' => 4,
                'avg_rating' => '2.00',
                'country_code' => 'IN',
                'mobile' => '917078787466',
                'ref_by' => 0,
                'balance' => '0.00000000',
                'password' => '$2y$12$5C6CqtlABHNxyzQfHgBnmO74aSBz/wAffsrTonOiRNbJNFBjC9JFq',
                'image' => NULL,
                'address' => '{"address":"4, 6th Floor, Building 2, Candor Techspace","city":"Noida","state":"Uttar pradesh","zip":"201309","country":"India"}',
                'status' => 1,
                'kyc_data' => NULL,
                'kv' => 1,
                'ev' => 1,
                'sv' => 1,
                'reg_step' => 1,
                'ver_code' => '258845',
                'ver_code_send_at' => '2024-11-20 18:18:14',
                'ts' => 0,
                'tv' => 1,
                'tsc' => NULL,
                'ban_reason' => NULL,
                'remember_token' => NULL,
                'created_at' => '2024-11-18 17:19:41',
                'updated_at' => '2024-11-20 23:48:14',
            ),
            3 => 
            array (
                'id' => 4,
                'firstname' => 'sandeep',
                'lastname' => 'verma',
                'username' => 'sandeepv',
                'email' => 'sandipva55@gmail.com',
                'total_review' => 2,
                'avg_rating' => '5.00',
                'country_code' => 'IN',
                'mobile' => '917303800275',
                'ref_by' => 0,
                'balance' => '17.80000000',
                'password' => '$2y$10$CNX5PaJEnuxXJA818s5iouzm5V/D4z6TiM.l8BtaN06KMXjEPqJA2',
                'image' => NULL,
                'address' => '{"country":"India","address":"noida","state":"uttra pradesh","zip":"201309","city":"greater noida west"}',
                'status' => 1,
                'kyc_data' => NULL,
                'kv' => 1,
                'ev' => 1,
                'sv' => 1,
                'reg_step' => 1,
                'ver_code' => '217722',
                'ver_code_send_at' => '2024-11-18 11:55:47',
                'ts' => 1,
                'tv' => 0,
                'tsc' => NULL,
                'ban_reason' => NULL,
                'remember_token' => NULL,
                'created_at' => '2024-11-18 17:23:14',
                'updated_at' => '2024-12-11 23:56:57',
            ),
            4 => 
            array (
                'id' => 5,
                'firstname' => 'Mohit',
                'lastname' => 'Suri',
                'username' => 'momen_s',
                'email' => 'm@gmail.com',
                'total_review' => 1,
                'avg_rating' => '4.00',
                'country_code' => 'BD',
                'mobile' => '918804565378',
                'ref_by' => 0,
                'balance' => '0.00000000',
                'password' => '$2y$10$w6TkElZJXy9dDziF4AXvxe8HdNkPzpEdPg4ct5ckl8zh6q4.eCiPq',
                'image' => NULL,
                'address' => '{"address":"5, 6th Floor, Building 2, Candor Techspace","city":"Noida","state":"Uttar pradesh","zip":"201309","country":"India"}',
                'status' => 1,
                'kyc_data' => NULL,
                'kv' => 0,
                'ev' => 1,
                'sv' => 1,
                'reg_step' => 1,
                'ver_code' => NULL,
                'ver_code_send_at' => NULL,
                'ts' => 0,
                'tv' => 1,
                'tsc' => NULL,
                'ban_reason' => NULL,
                'remember_token' => NULL,
                'created_at' => '2024-11-18 20:26:35',
                'updated_at' => '2024-11-18 20:26:47',
            ),
            5 => 
            array (
                'id' => 6,
                'firstname' => 'Prashant',
                'lastname' => 'Chauhan',
                'username' => 'webreca',
                'email' => 'webreca@gmail.com',
                'total_review' => 5,
                'avg_rating' => '4.00',
                'country_code' => 'IN',
                'mobile' => '919999577620',
                'ref_by' => 0,
                'balance' => '304.90000000',
                'password' => '$2y$12$5C6CqtlABHNxyzQfHgBnmO74aSBz/wAffsrTonOiRNbJNFBjC9JFq',
                'image' => NULL,
                'address' => '{"address":"5, 6th Floor, Building 2, Candor Techspace","city":"Noida","state":"Uttar pradesh","zip":"201309","country":"India"}',
                'status' => 1,
                'kyc_data' => NULL,
                'kv' => 1,
                'ev' => 1,
                'sv' => 1,
                'reg_step' => 1,
                'ver_code' => NULL,
                'ver_code_send_at' => NULL,
                'ts' => 0,
                'tv' => 1,
                'tsc' => NULL,
                'ban_reason' => NULL,
                'remember_token' => NULL,
                'created_at' => '2024-11-18 20:26:35',
                'updated_at' => '2024-12-24 17:48:24',
            ),
            6 => 
            array (
                'id' => 7,
                'firstname' => 'Kailash',
                'lastname' => 'Singh',
                'username' => 'kailash',
                'email' => 'kailashsinghh3312@gmail.com',
                'total_review' => NULL,
                'avg_rating' => NULL,
                'country_code' => 'IN',
                'mobile' => '919999995566',
                'ref_by' => 0,
                'balance' => '0.00000000',
                'password' => '$2y$12$5C6CqtlABHNxyzQfHgBnmO74aSBz/wAffsrTonOiRNbJNFBjC9JFq',
                'image' => NULL,
                'address' => '{"address":"","state":"","zip":"","country":"India","city":""}',
                'status' => 1,
                'kyc_data' => NULL,
                'kv' => 0,
                'ev' => 1,
                'sv' => 1,
                'reg_step' => 1,
                'ver_code' => '779050',
                'ver_code_send_at' => '2024-12-08 18:10:01',
                'ts' => 0,
                'tv' => 1,
                'tsc' => NULL,
                'ban_reason' => NULL,
                'remember_token' => NULL,
                'created_at' => '2024-12-08 23:40:01',
                'updated_at' => '2024-12-08 23:40:01',
            ),
            7 => 
            array (
                'id' => 8,
                'firstname' => 'Prashant',
                'lastname' => 'Chauhan',
                'username' => 'johndoe',
                'email' => 'john@gmail.com',
                'total_review' => NULL,
                'avg_rating' => NULL,
                'country_code' => 'IN',
                'mobile' => '91955512087',
                'ref_by' => 0,
                'balance' => '0.00000000',
                'password' => '$2y$10$Uek7s5qFvjeyzWrV2E28ZuafG124E6tj1JIm6jDTpJl/N46yFMdKa',
                'image' => NULL,
                'address' => '{"address":"C-6, Sector 7","city":"Noida","state":"Uttar Pradesh","zip":"201301","country":"India"}',
                'status' => 1,
                'kyc_data' => '[{"name":"Full Name","type":"text","value":"Drake Richmond"},{"name":"NID Number","type":"text","value":"262370258887"},{"name":"Gender","type":"select","value":"Male"},{"name":"You Hobby","type":"checkbox","value":["Traveling"]},{"name":"NID Photo","type":"file","value":"2024\\/12\\/18\\/676280e214a9b1734508770.jpg"},{"name":"Mobile","type":"text","value":"9874589658"}]',
                'kv' => 1,
                'ev' => 1,
                'sv' => 1,
                'reg_step' => 1,
                'ver_code' => NULL,
                'ver_code_send_at' => NULL,
                'ts' => 0,
                'tv' => 1,
                'tsc' => NULL,
                'ban_reason' => NULL,
                'remember_token' => NULL,
                'created_at' => '2024-12-18 19:25:07',
                'updated_at' => '2024-12-18 19:30:11',
            ),
            8 => 
            array (
                'id' => 9,
                'firstname' => 'Mohit',
                'lastname' => 'Parwal',
                'username' => 'mohitparwal2127',
                'email' => 'mohitparwal2127@gmail.com',
                'total_review' => NULL,
                'avg_rating' => NULL,
                'country_code' => 'IN',
                'mobile' => '918810317159',
                'ref_by' => 0,
                'balance' => '0.00000000',
                'password' => '$2y$10$LzrYbZBQTfYzqxyE28OR9O9HrClpOEtFI7DFlwTosWrZV4Kd3vIQu',
                'image' => NULL,
                'address' => '{"address":"Sector 21 Gurgaon Haryana","city":"Gurgaon","state":"Haryana","zip":"122016","country":"India"}',
                'status' => 1,
                'kyc_data' => '[{"name":"Full Name","type":"text","value":"Beldiwers Tower"},{"name":"NID Number","type":"text","value":"56141561458"},{"name":"Gender","type":"select","value":"Male"},{"name":"You Hobby","type":"checkbox","value":["Programming"]},{"name":"NID Photo","type":"file","value":"2024\\/12\\/29\\/677110099c9ef1735462921.png"},{"name":"Mobile","type":"text","value":"8810317159"}]',
                'kv' => 1,
                'ev' => 1,
                'sv' => 1,
                'reg_step' => 1,
                'ver_code' => NULL,
                'ver_code_send_at' => NULL,
                'ts' => 0,
                'tv' => 1,
                'tsc' => NULL,
                'ban_reason' => NULL,
                'remember_token' => NULL,
                'created_at' => '2024-12-29 20:00:12',
                'updated_at' => '2024-12-29 20:03:35',
            ),
            9 => 
            array (
                'id' => 10,
                'firstname' => 'Naman',
                'lastname' => 'Yadav',
                'username' => 'prnav01@gmail.com',
                'email' => 'prnav01@gmail.com',
                'total_review' => NULL,
                'avg_rating' => NULL,
                'country_code' => NULL,
                'mobile' => NULL,
                'ref_by' => 0,
                'balance' => '22.76000000',
                'password' => '$2y$10$e5AOP0bROx1WF/Pn7TWGdO7rurIYv0B35LqKtaPVRAaxVtY0Ns7/2',
                'image' => NULL,
                'address' => '{"country":null,"address":"Dwarka","state":"New Delhi","zip":"110078","city":"Dwarka"}',
                'status' => 1,
                'kyc_data' => '[{"name":"Full Name","type":"text","value":"Naman Yadav"},{"name":"NID Number","type":"text","value":"984984498894"},{"name":"Gender","type":"select","value":"Male"},{"name":"You Hobby","type":"checkbox","value":["Programming"]},{"name":"NID Photo","type":"file","value":"2024\\/12\\/29\\/6771148bb212b1735464075.png"},{"name":"Mobile","type":"text","value":"88103178159"}]',
                'kv' => 1,
                'ev' => 1,
                'sv' => 1,
                'reg_step' => 1,
                'ver_code' => NULL,
                'ver_code_send_at' => NULL,
                'ts' => 0,
                'tv' => 1,
                'tsc' => NULL,
                'ban_reason' => NULL,
                'remember_token' => NULL,
                'created_at' => '2024-12-29 20:20:06',
                'updated_at' => '2024-12-29 20:45:17',
            ),
            10 => 
            array (
                'id' => 11,
                'firstname' => NULL,
                'lastname' => NULL,
                'username' => 'mohitparwal2103@gmail.com',
                'email' => 'mohitparwal2103@gmail.com',
                'total_review' => NULL,
                'avg_rating' => NULL,
                'country_code' => NULL,
                'mobile' => NULL,
                'ref_by' => 0,
                'balance' => '0.00000000',
                'password' => '$2y$10$TE8o3VPAfbNqJjfeqC6roe0t1LBmPldFzqm2F.5n7TioFXmBRAMtu',
                'image' => NULL,
                'address' => '{"address":"","state":"","zip":"","country":null,"city":""}',
                'status' => 1,
                'kyc_data' => NULL,
                'kv' => 0,
                'ev' => 1,
                'sv' => 1,
                'reg_step' => 0,
                'ver_code' => NULL,
                'ver_code_send_at' => NULL,
                'ts' => 0,
                'tv' => 1,
                'tsc' => NULL,
                'ban_reason' => NULL,
                'remember_token' => NULL,
                'created_at' => '2024-12-29 20:45:47',
                'updated_at' => '2024-12-29 20:45:47',
            ),
            11 => 
            array (
                'id' => 12,
                'firstname' => 'Prashant Singh',
                'lastname' => 'Chauhan',
                'username' => 'sales@webreca.com',
                'email' => 'sales@webreca.com',
                'total_review' => NULL,
                'avg_rating' => NULL,
                'country_code' => NULL,
                'mobile' => NULL,
                'ref_by' => 0,
                'balance' => '0.00000000',
                'password' => '$2y$10$NO76Aguu8RWgSxVbcVsCOOEYpsN7mapN.KQD/3JkI1QJoc8NhJFe.',
                'image' => NULL,
                'address' => '{"country":null,"address":"M-4, New Police Line","state":"Delhi","zip":"110009","city":"Delhi"}',
                'status' => 1,
                'kyc_data' => NULL,
                'kv' => 0,
                'ev' => 1,
                'sv' => 1,
                'reg_step' => 1,
                'ver_code' => NULL,
                'ver_code_send_at' => NULL,
                'ts' => 0,
                'tv' => 1,
                'tsc' => NULL,
                'ban_reason' => NULL,
                'remember_token' => NULL,
                'created_at' => '2025-01-03 02:10:37',
                'updated_at' => '2025-01-03 02:11:58',
            ),
        ));
        
        
    }
}